apiVersion: apps/v1
kind: Deployment
metadata:
  name: calorie-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calorie-tracker
  template:
    metadata:
      labels:
        app: calorie-tracker
    spec:
      containers:
      - name: calorie-tracker
        image: calorie-tracker
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: calorie-tracker-service
spec:
  type: NodePort
  selector:
    app: calorie-tracker
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
